### ISSUE TITLE
Fails on 32-bit OS

### ISSUE THREAD

**Issue by ghost** [snielsen/DeathToDSStore#1]

**Comment by wyatt8740** [comment]
why not? some mac's have 64 bit CPU's but literally cannot run 64 bit OS X due to 32 bit EFI. Please reconsider?

**Comment by wyatt8740** [comment]
also, how hard would it be? I REALLY hate .DS_Store, and I don't want to buy a new computer JUST so I don't see them everywhere... I have some C experience but I always get nervous with hacking other programs, and have never done so in OS X (only windows and linux).

**Comment by snielsen** [comment]
It has been a few years since I wrote the original code and so in the cobwebs in my mind I think there may have been a dependency that was only 64-bit (I could be misremembering though). Even if all the dependencies do exist in 32-bit versions, there are still some sections that would probably need 32-bit specific modifications and testing. I don't have the bandwidth for that at the moment and I figured that even if there are still a lot of 32-bit machines in the wild, over time everything is eventually going to be 64-bit. 

That said, I would never discourage you from forking the project and trying your hand at 32-bit support yourself :) Maybe it would be easier to implement than I thought?

**Comment by wyatt8740** [comment]
Well, I have no experience with Mach injection. I barely even have experience with OS X at low levels. And my mac is pretty old, and it shows - OS X 10.6 and XCode 4.2. Integrated GMA 950 graphics, so the 64 bit kernel is barely functional.

Anyway, I can try, but only if when I am at the mac I learn that this project can build in Xcode 4.2.
