### ISSUE TITLE
Support for OS 10.11

### ISSUE THREAD

**Issue by borisdiakur** [snielsen/DeathToDSStore#3]
DeathToDSStore doesn't seem to work under El Capitan.

**Comment by snielsen** [comment]
Yes, the new System Integrity Protection feature in El Capitan prevents both filesystem and runtime modification of the operating system. You can turn it off and Death To .DS_Store will work again. Ultimately I am still holding out hope that Apple will do the right thing and fix it someday :)

Spencer

**Comment by borisdiakur** [comment]
Would it work, if I turned of System Integrity Protection, installed the Death To .DS_Store Launch Agend, then turned it back on again?

**Comment by snielsen** [comment]
Unfortunately not. The thing that Death To .DS_Store needs to be able to do is runtime modification of the Finder process. As long as System Integrity Protection is turned on then process injection is not permitted on the Finder or any other OS process. Sorry :( 

Spencer

**Comment by zbstof** [comment]
If someone like me came here for the solution to the problem, you can look here:
http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/

Here's the steps:
1. Reboot into recovery mode: Hold Control+R immediately after startup chime sounds
2. In Terminal, run `csrutil disable; reboot`

Check rootless status with `csrutil status`

**Comment by snielsen** [comment]
Just to close the loop here, you can still use Death To .DS_Store on 10.11 if you disable System Integrity Protection (SIP). 

I can't openly recommend that people do that, but power users that know what they are doing can accept the risk on their own. I have personally done so on my own systems so that I can continue to suppress .DS_Store creation but also because SIP seems to screw up a lot of other stuff like virtualization of Boot Camp, etc.

**Comment by jhabdas** [comment]
I'm on El Capitan 10.11.6 (15G31) and did nothing in the way of disabling SIP and this app seems to be functioning just fine.
